version: 2.1
jobs:
  build_frontend:
    working_directory: $CIRCLE_WORKING_DIRECTORY/fo-frontend
    docker:
      - image: circleci/node:11.9.0-browsers
    steps:
      - checkout

      - restore_cache:
          name: Restore yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn install
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: ls -al

      - run:
          name: Build project
          command: yarn build

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build_frontend
