version: 2.1
jobs:
  build_frontend:
    docker:
      - image: circleci/node:11.9.0-browsers
    steps:
      - checkout

      - restore_cache:
          name: Restore yarn package cache
          key: yarn-packages-{{ checksum "fo-frontend/yarn.lock" }}

      - run:
          name: Yarn install
          command: cd fo-frontend; yarn install --frozen-lockfile

      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "fo-frontend/yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: "Run tests"
          command: cd fo-frontend; yarn test

      - run:
          name: Build project
          command: cd fo-frontend; yarn build

  deploy:
    steps:
      - run:
          name: Deploy
          command: mvn deploy -s .circleci/settings.xml -Dmaven.skip.fe=true

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build_frontend
      - deploy
        - requires:
            - build_frontend
