version: 2.1
jobs:
  build_frontend:
    docker:
      - image: circleci/node:9.9.0-browsers
    steps:
      - checkout

      - restore_cache:
          name: Restore cache
          keys:
            - dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Yarn install
          command: yarn install

      - save_cache:
          name: Save cache
          keys:
            - dependency-cache-{{ checksum "package.json" }}

      - run: ls -al

      - run:
          name: Build project
          command: yarn build

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build_frontend
