# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build_it:
    working_directory: ~/
    docker:
      - image: circleci/openjdk:8-jdk-stretch-node-browsers
    steps:
      - run:
          name: Path
          command: pwd
      - run:
          name: ls
          command: ls -al
      - run:
          name: 'Yarn install'
          command: 'yarn install'
      - run:
          name: 'Build project'
          command: yarn build

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  # Name the workflow "Welcome"
  Welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build_it
